### ISSUE TITLE
React Native version mismatch. JavaScript version: 0.61.5 Native version: 0.62.0

### ISSUE THREAD

**Issue by akshgods** [WrathChaos/react-native-gradient-card-view#36]
Getting this error after importing "react-native-gradient-card-view" 
console.error: React Native version mismatch.
JavaScript version: 0.61.5
Native version: 0.62.0

package json:
 "dependencies": {
    "@freakycoder/react-native-helpers": "^0.1.3",
    "@react-native-community/async-storage": "^1.10.0",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-navigation/material-bottom-tabs": "^5.2.1",
    "@react-navigation/native": "^5.2.6",
    "@react-navigation/stack": "^5.2.8",
    "lottie-ios": "^3.1.3",
    "lottie-react-native": "^3.3.2",
    "react": "16.11.0",
    "react-native": "0.62.0",
    "react-native-animatable": "^1.3.3",
    "react-native-animation-layout": "0.0.13",
    "react-native-dynamic-search-bar": "^1.0.3",
    "react-native-dynamic-vector-icons": "^0.1.1",
    "react-native-fast-image": "^8.1.5",
    "react-native-gesture-handler": "^1.6.1",
    "react-native-gradient-card-view": "^0.2.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-paper": "^3.10.1",
    "react-native-reanimated": "^1.7.1",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.4.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-svg": "^12.1.0",
    "react-native-svg-charts": "^5.4.0",
    "react-native-swiper": "^1.6.0",
    "react-native-vector-icons": "^6.6.0",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5"
  },

**Comment by WrathChaos** [comment]
Hello @akshgods,
This is not an issue related to this library. Here is the answer from Stackoverflow.
https://stackoverflow.com/questions/47763824/react-native-version-mismatch
