### ISSUE TITLE
Expo module not found

### ISSUE THREAD

**Issue by dmongit** [WrathChaos/react-native-gradient-card-view#6]
I get an error that react-native-gradient-card-view cannot resolve module 'expo'.

I run `C:\folder\app\android> ./gradlew assembleRelease`

I get this error: `error Unable to resolve module `expo` from `node_modules\react-native-gradient-card-view\lib\src\components\GradientCard.js`: expo could not be found within the project.`

I'm not using Expo. I followed the instructions to install dependencies, and the read me of those dependencies to install everything I need. I think I have everything I need, but here is what I have:

  "dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.0-rc.0",
    "react-native-animation-layout": "^0.0.13",
    "react-native-dynamic-search-bar": "^0.2.0",
    "react-native-fast-image": "^7.0.2",
    "react-native-gradient-card-view": "^0.0.2",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-svg": "^9.7.1",
    "react-native-svg-charts": "^5.3.0"
  },

**Comment by WrathChaos** [comment]
Hello @dmongit,
I'm working on it :)

**Comment by WrathChaos** [comment]
@dmongit Found the problem. Publishing new release with a new example :)

**Comment by WrathChaos** [comment]
@dmongit I published the new release. Tested on iOS however could not test it on Android. Can you test it and give me the feedback please? 

## [Release 0.1.0](https://github.com/WrathChaos/react-native-gradient-card-view/releases/tag/0.1.0)🎉

**Comment by dmongit** [comment]
@WrathChaos sweet! great response and fix time. I'll get back to you when I have a chance to test. It might be several hours though.

**Comment by dmongit** [comment]
@WrathChaos I think I got farther, but a new Android bug.

`Error: Unable to resolve module `react-native-iphone-x-helper` from `node_modules\react-native-dynamic-search-bar\lib\src\SearchBar.style.js`: react-native-iphone-x-helper could not be found within the project.`

Here are my dependencies now (a few new ones b/c I was also trying something else, but your bitcoin example has this search bar, so I think this is you? Would you rather I open a bug in that repo?

  ```
"dependencies": {
    "react": "16.9.0",
    "react-native": "0.61.0-rc.0",
    "react-native-animation-layout": "^0.0.13",
    "react-native-dynamic-search-bar": "^0.2.0",
    "react-native-dynamic-vector-icons": "^0.1.0",
    "react-native-fast-image": "^7.0.2",
    "react-native-gradient-card-view": "^0.1.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-svg": "^9.7.1",
    "react-native-svg-charts": "^5.3.0",
    "react-native-vector-icons": "^6.6.0"
  },
```

**Comment by WrathChaos** [comment]
@dmongit Glad to know that it works for you :)
