### ISSUE TITLE
Unable to resolve "react-native-easy-cached-image"

### ISSUE THREAD

**Issue by hani-q** [WrathChaos/react-native-gradient-card-view#9]
Hi,

Added the dependency as mentioned.. here is my package.json

  "dependencies": {
    "@react-native-community/masked-view": "^0.1.5",
    "expo": "~36.0.0",
    "expo-blur": "~8.0.0",
    "firebase": "^7.8.2",
    "formik": "^1.5.8",
    "moment": "^2.24.0",
    "react": "^16.12.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-calendar-strip": "^1.4.1",
    "react-native-elements": "^1.2.7",
    "react-native-expo-image-cache": "^4.1.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-native-gradient-buttons": "^2.0.1",
    "react-native-gradient-card-view": "WrathChaos/react-native-gradient-card-view#expo",
    "react-native-reanimated": "~1.4.0",
    "react-native-safe-area-context": "^0.6.0",
    "react-native-screens": "2.0.0-alpha.12",
    "react-native-swipe-gestures": "^1.0.4",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.1.1",
    "react-navigation-stack": "^2.1.1",
    "react-navigation-tabs": "^2.7.0",
    "yup": "^0.28.1"
  }

But as soon as i expo and goto the needed screeen i see

Unable to resolve "react-native-easy-cached-image" from "node_modules\react-native-gradient-card-view\lib\src\components\GradientCard.js"
Failed building JavaScript bundle.

Any ideas ?

**Comment by WrathChaos** [comment]
Hello @hani-q,
You can install `react-native-easy-cached-image` but I can remove this dependency. I can inform you ASAP.
